# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'swift-SBPickerSelectorExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SBPickerSelector', :path => '../'
  # Pods for swift-SBPickerSelectorExample

end
